version: '3.8'

services:
  frontend:
    container_name: frontend
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:80

  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 3001:3000
